### ISSUE TITLE
Question: How to minimize the border?

### ISSUE THREAD

**Issue by Lcng** [codebude/QRCoder#101]
The generated image has a big blank border. How to minimize it? Thank you very much.

**Comment by Hydroque** [comment]
You can drag and drop images into github comment here and it will let us see what you mean. Assuming 'border' as the area around the block area, you might have your settings wrong.

**Comment by codebude** [comment]
Hi @Lcng ,

the "border" around the code-part is the so called "Quiet Zone". It's part of the official QR code specification. Nevertheless, since you're not the only one who didn't want it, I added a parameter to remove the border.

Just set the *drawQuietZones* parameter of the **GetGraphic()**-method to false. More information can be found in the wiki: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#21-qrcode-renderer-in-detail

Please let me know, if this solved your problem.

**Comment by Lcng** [comment]
Hi @Hydroque 
Sorry for my pool English. ‘Border' means 'Quiet Zone' as codebude said. And codebude anwsered my question.

**Comment by Lcng** [comment]
Thank you @codebude 
You solved my problem, and let me know the 'border' is 'Quiet Zone'. Thank you very much.

**Comment by codebude** [comment]
@Lcng no problem. By the way - it is indeed a border. Just this kind of border in QR Codes is called QuietZone.

**Comment by Hydroque** [comment]
@Lcng Your english isn't bad at all, by all means. It just lacked a lot of context and explanation.
