### ISSUE TITLE
Mistake in QRCoderCosole code

### ISSUE THREAD

**Issue by tadam98** [codebude/QRCoder#102]
## Type of issue
[*] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior

QRCoder should use text from file. Instead it always uses the payload.

## Possible Solution (optional)

**Bug** Line 122:  GenerateQRCode(**payload**, eccLevel, outputFileName, imageFormat, pixelsPerModule, foregroundColor, backgroundColor);

**New** Line 122:  GenerateQRCode(**text**, eccLevel, outputFileName, imageFormat, pixelsPerModule, foregroundColor, backgroundColor);
        

## Steps to Reproduce (for bugs)

**Execute:** 'QRCodeConsole.exe -i QR-sample2.txt --output-format=jpg -o QR-sample2.jpg'
Before correction there is an exception because "payload" parameter was not set (because input file is wanted)

**Comment by Hydroque** [comment]
Is this from master?

**Comment by codebude** [comment]
Hi @tadam98 ,

thanks for your input. You're totally right. Since the payload, regardless if given as string parameter or coming from a textfile, is mapped to the text variable, it should be used in line 122. I've fixed it in the master branch.

@Hydroque - yes, this was from master. You can see it in the history: https://github.com/codebude/QRCoder/blob/939a92624fcbb1395368757146bfa69592753013/QRCoderConsole/Program.cs
