### ISSUE TITLE
Signed Package ?

### ISSUE THREAD

**Issue by AvastianOttawa** [codebude/QRCoder#126]
I am looking to integrate this into my Project, however i noticed the nuget manager package downloaded is unsigned, do you have advice on how to generate my dll and if i can sign it or what the best way to use your library is? I want to make sure you get credit where credit is due and that I do not do anything incorrectly thank you

**Comment by codebude** [comment]
Hi @AvastianOttawa ,

since Nuget packages are built automatically from this Github repo and I don't want to upload my private key here, there is no signed/strong named version of this library on Github. If you need one, just clone/fork or download this Github repository and compile it with your own private key, like proposed here: #54

**Comment by codebude** [comment]
Hi @MatejQ 

> then how other developers do it when they offer strong named assemblies in their nuget packages?

That's a good question... The current set-up looks like this:

- All development is done by use of Github.
- The project gets automatically built via myget.org, everytime a commit is pushed to Github.
- This automatically (dev) builds are published via myget's nuget stream.
- Everytime I want to publish a stable release, I take the latest myget build and let myget push the package to Nuget.

To bring in signing into this process, the private key had to be published on Github or atleast linked in the build scripts (which are also taken by myget from Github). So I had to publish the private key, which would make the whole effort silly, because everyone could take the key and publish their own "orginal" QRCoder versions.

One option would be to break the publishing process, by downloading the latest MyGet package, sign it local and then publish it manually on Nuget. Let me think about it for a while.

In general, if you can't wait, you could sign the assembly yourself with projects like: https://github.com/brutaldev/StrongNameSigner 

> Having a strong named assembly is important.

How important can it be, when:

-  a) there is the possibility to sign it yourself
-  b) the package is downloaded over 150.000 times

I don't want to say, that signed packages may be needed sometimes, but 99% of the projects I've seen/I've worked with were unsigned. The only reason to sign a package, was because a project itself was signed and therefore was in need of a signed package...

**Comment by MatejQ** [comment]
Well, the last thing you mentioned is in fact true in the project I am developing. It's strongly named and can reference only strongly-named assemblies. Of course we could build QRCoder ourselves and use that, but then we would lose all the benefits coming from usage of nuget, such as notification and one-click install of new versions.
I said having strongly named version is important because there are repeating requests from users like me. At first I installed QRCoder, implemented code according to examples, and when I tried to build it, I got error that it is not strongly named.
If anyone else stumbles upon this thread, I can recommend alternative nuget package that can also generate QR codes and is strongly named. Its name is ZXIng.Net and it is what we ended up using.

**Comment by nitrovent** [comment]
@MatejQ 
In my company we're working on projects that also need to be strongly named. 
Our solution for libraries like QRCoder (and others like NewtonSoft's Json.Net) is to include their Nuget packages in an internal package named (OurProduct).ExternalLibrary and then sign this library. This way we do not need to compile and sign the indiviual libraries our self.
PS: The external library merges the assemblies into one assembly preserving while the namespaces using ILMerge, wich is also available as a Nuget package.
