### ISSUE TITLE
Support center logo/Image on uwp platform

### ISSUE THREAD

**Issue by hupo376787** [codebude/QRCoder#136]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  

## Expected Behavior

Support center logo/Image on uwp platform.

![image](https://user-images.githubusercontent.com/14960168/43885792-7fa62f42-9bec-11e8-93be-16431f0e1951.png)

**Comment by codebude** [comment]
I assume, that @hupo376787 used [BitmapByteQRCode](https://github.com/codebude/QRCoder/blob/master/QRCoder/BitmapByteQRCode.cs) for his UWP project. So that task would be to implement an additional overload, which takes an exisiting image and renders it onto the Bitmap.

**@All:** Since I'm in lack of time, help is appreciated. Feel free to support this project, by implementing this feature and sending in a pull request.

**Comment by BugAgain** [comment]
PCL is deprecated. Any chance of migrating to .NET Standard?

**Comment by codebude** [comment]
The Nuget package already contains net core/standard DLLs.

**Comment by BugAgain** [comment]
I'm not very good at working with graphics in C#, but I believe the effort to support PCL also wouldn't compensate. That's why I asked if it would be better to upgrade to .Net Standard instead of using PCL in existing projects. Also, how about we have that exemple using PCL updated with .Net Standard. What do you think?

**Comment by codebude** [comment]
Since there was never a feedback from the issue opener and no general interest in this feature, this issue will be close for now.
