### ISSUE TITLE
Bitmap qrCodeImage documentation example error.

### ISSUE THREAD

**Issue by JacobChrist** [codebude/QRCoder#138]
## Type of issue
[ ] Documentation error

## Expected Behavior
In the readme.md in section: Optional parameters and overloads

This call doesn't work (any more?).  It needs a forth parameter:

Bitmap qrCodeImage = qrCode.GetGraphic(20, Color.DarkRed, Color.PaleGreen);

## Possible Solution (optional)
Bitmap qrCodeImage = qrCode.GetGraphic(20, Color.DarkRed, Color.PaleGreen, true);

I'm using commit: 1be41a1403883687b14eac4fe617ff07043fa192 in VS2017 CE

Nice easy to use lib, thanks.

**Comment by codebude** [comment]
Hi Jacob,

you're right. In theory this function call should work, as the fourth parameter is defined with a default value.
![optional overload](https://user-images.githubusercontent.com/2236234/46742906-43457e80-cca8-11e8-8f20-35cdf90add69.png)

In theory you can't use it, because in the meantime some other overloads came, which lead to ambiguity when called just with three parameters.

Long story short, I fixed the documentation. Thanks for your feedback!
