### ISSUE TITLE
Extending Payload

### ISSUE THREAD

**Issue by smartmeter** [codebude/QRCoder#14]
Hello, great lib BTW!

Can you share how to extend the Payload to implement a custom Payload action. For e.g. send to printer or send to image.

thanks

**Comment by codebude** [comment]
Hey smartmeter,

there is no "custom payload" for send to printer, etc. The payload types I implemented, were payloads which are some kind of standard and known by the most QR readers. Which means, they're working just because the QR code readers can interpret this kind of payload.

A QR code exists only of text. To trigger a "send to printer" event, the reader has to implement it. Because there's no standard payload type for this, the readers also can't trigger it.

The only solution I can think of, would be the following:
You define your own payload type and implement your own QR code reader, which can interpret this type of payload.
