### ISSUE TITLE
QRCoder on Unity generate code but phone app QRreader not read information

### ISSUE THREAD

**Issue by sergipanadero** [codebude/QRCoder#15]
Hi,

I'm using your code on a Unity Standalone aplicación. I can generate the QR code and assing to a texture, but my pone App QRReader not read any information. I want to generate a QR of a url.

my code is 

`
	public void QR2()
	{
		QRCodeGenerator qrGenerator = new QRCodeGenerator();
		PayloadGenerator.Url urlPayload = new PayloadGenerator.Url("http://www.google.es");
		QRCodeData qrCodeData = qrGenerator.CreateQrCode(urlPayload.ToString(), QRCodeGenerator.ECCLevel.Q);
		UnityQRCode qrCode = new UnityQRCode(qrCodeData);
		Texture2D qrCodeImage = qrCode.GetGraphic(50);
		GetComponent<Renderer> ().material.mainTexture = qrCodeImage;
	}
`
what i'm doing worng? 
Thanks you

**Comment by alexnsfx** [comment]
The bug seems to be dependent of the application used.

Tested with your code and the following apps on Android :
OK https://play.google.com/store/apps/details?id=com.google.zxing.client.android
OK https://play.google.com/store/apps/details?id=com.gamma.scan
UNREADABLE https://play.google.com/store/apps/details?id=me.scan.android.client
UNREADABLE https://play.google.com/store/apps/details?id=la.droid.qr

**Comment by codebude** [comment]
Fixed in https://github.com/codebude/QRCoder/commit/7880bbfad743cc7c193764d7e45b44d19a3e4622

Successful tested with all 4 QR code readers. If you have still problems, please re-open the issue.
