### ISSUE TITLE
qrCode.GetGraphic(20) doubt.

### ISSUE THREAD

**Issue by FranciscoKloganB** [codebude/QRCoder#152]
I don't understand how exactly the QRCode.GetGraphics works and I've sort of blazed through the available documentation.

I am using the QR Code package to create a qr-code representation of a Public Key that will be photographed by an Android App and later used for secure communication. As such, the image needs to be as accurate as possible as the loss of a single byte on the key sequence will make the whole protocol fail. Mind you that this is experimental at least on my part and I don't know how reliable it would be.

Anywawy, the QR Code image is being done on a Windows Forms .NET Framework Application and I would just like to understand why all examples use:

Bitmap qrCodeImage = qrCode.GetGraphic(20);

And how passing an higher or lower value impacts image quality. Maybe it's a dumb question but I would still like some clarification.

**Comment by codebude** [comment]
Hi @FranciscoKloganB ,

a QR code consists out of black and white "blocks", the so-called "modules". The more data/information you like to store in a QR code (=the longer your input string is), the more blocks are needed to store the information.

The GetGraphic-functions takes a matrix of modules information (x position, y position, color (black/white)) and create the actual QR Code image out of it. The QR code image is a Bitmap (at least for the "QRCode" class). Bitmaps consist out of pixels. The parameter (e.g. 20) says how much pixels will be used to draw a single module.

For example if you create a QR code which has 20x20 modules and you call GetGraphics(20) then you get a bitmap file with the dimensions of 400x400 px.
You should use the parameter this way, that the outcoming QR code graphic can be shown in its native resolution. Otherwise if you app/picturebox/whatever you use stretches the image oder scales it down, it may become blurry and harder to read for QR code scanners.

In Theory you could also call GetGraphic(1), but then the reader's camera must be able to take such high resolution images that it can capture each an every pixel of your QR code graphic. So it isn't a good idea to use GetGraphic(1). Just try around, how small you can go, while keeping the ability to read the QR code. (In practice it may be a good idea too choose the space which is available in your app. Even if your tests show that you could draw the QR code smaller and it is still readable, maybe not all users/customers have that good hardware like you. ;-) )

> As such, the image needs to be as accurate as possible as the loss of a single byte on the key sequence will make the whole protocol fail. 

This can't happen with QR codes. QR codes have some kind of checksum feature. Either they can be read (totally and correct) or they can't be read. As explained above - when choosing the image size that fits your needs, just check if the QR code keeps readable.

**Comment by FranciscoKloganB** [comment]
Great explanation. Thanks alot for the help. It's now clear as water. :)
💯 👍

**Comment by codebude** [comment]
Thanks for your kind words. So I'll close this issue.

**Comment by JONI19999** [comment]
@codebude  so if I increase the pixelsPerModule this will be more easy to reader to read this qrocde?
Why in code do you set 20?
how much "blocks" is there in qrcode? is that constant or depend in the length of data I want to encode?

thank you!
