### ISSUE TITLE
Does not produce working QR Codes for vCards

### ISSUE THREAD

**Issue by JunkyXL86** [codebude/QRCoder#166]
## Type of issue
[x] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
Working QR Codes generated from vCard files

## Current Behavior
Produces QR Code that is not readable by any QR Reader (does nothing)

## Steps to Reproduce (for bugs)
Using this vCard:
```
BEGIN:VCARD
VERSION:2.1
N;LANGUAGE=en:Doe;John
FN:John Doe
ORG:Contoso
TITLE:Software Engineer
TEL;WORK;VOICE:+11 12345678
TEL;CELL;VOICE:+11 4567890
ADR;WORK;PREF:;;Work St 1;Anaheim;;123456;USA
LABEL;WORK;PREF;ENCODING=QUOTED-PRINTABLE:Work St 1=0D=0A=
=0D=0A=
123456  Anaheim
X-MS-OL-DEFAULT-POSTAL-ADDRESS:2
URL;WORK:www.contoso.com
EMAIL;PREF;INTERNET:John.Doe@contoso.com

X-MS-OL-DESIGN;CHARSET=utf-8:<card xmlns="http://schemas.microsoft.com/office/outlook/12/electronicbusinesscards" ver="1.0" layout="left" bgcolor="ffffff"><img xmlns="" align="fit" area="16" /><fld xmlns="" prop="name" align="left" dir="ltr" style="b" color="000000" size="10"/><fld xmlns="" prop="org" align="left" dir="ltr" color="000000" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="telcell" align="left" dir="ltr" color="d48d2a" size="8"><label align="right" color="626262">Mobile</label></fld><fld xmlns="" prop="email" align="left" dir="ltr" color="d48d2a" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="addrwork" align="left" dir="ltr" color="000000" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/></card>
REV:20190220T153736Z
END:VCARD
```

Using this code to generate an SVG file:
```
var qrGenerator = new QRCodeGenerator();
var vcardContents = File.ReadAllText(vcardFile);
var qrCodeData = qrGenerator.CreateQrCode(vcardContents, QRCodeGenerator.ECCLevel.H, requestedVersion: 2);
var qrCode = new SvgQRCode(qrCodeData);
var svg = qrCode.GetGraphic(20);
```

Additional Note: crashes when not providing `requestedVersion` parameter.

**Comment by codebude** [comment]
Hi @JunkyXL86 ,

the QR code gets corrupted, because of the `requestedVersion: 2`. This says that the QR code should get a fixed size whereby requestedVersion=2 is too small to hold all data of your input string. So the first step is to remove the requestedVersion parameter and let QRCoder decide the correct version.

As you have realized, without the parameter QRCode crashes. This is the result of the given payload (your VCard string) and the choosen error correction level `H`. The higher the error correction level, the more space is needed, which results in a higher QR Code version. The maximum QR code version is 40 (which means 40 black/white dots per row). The combination of high error correction (`QRCodeGenerator.ECCLevel.H`) and your relatively long payload results in a theoretical QR code version > 40. Since this is not allowed by QR definition the QRCoder throws an exception. To avoid this problem, lower the error correction level. (By using the next smallest ecc level `QRCodeGenerator.ECCLevel.Q` the resulting QR code version is 38 and you should get a working result.)

For more information about capacity of QR codes for different ECC levels, please consult the following table: https://www.qrcode.com/en/about/version.html

If the above didn't solve your problems, let me know and feel free to re-open this issue.
