### ISSUE TITLE
Unable to access QRCode, QRCode  qrCode = new QRCode(qrCodeData); Kindly let me know which namespace and dll need to install, I have already access System.Drawing and QRCoder.

### ISSUE THREAD

**Issue by SheriffKhan** [codebude/QRCoder#176]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment]
Hi @SheriffKhan ,

to help you I need more information. Especially regarding your environment (that's why the issue template contains the point "your environment" ;-) ) So on which platform and what do you develop?
(full .NET-Framework, .NET core, UWP, etc...)

If you're not using the classic "full" .NET-Framework, you have to keep in mind, that not all renderers are available as explained over here: https://github.com/codebude/QRCoder/issues/174#issuecomment-481806668

**Comment by SheriffKhan** [comment]
Hi @codebude,
I am using .Net framework 4.5, and using this in a library project with Web API 2 application.

Still you want some other detail, kindly let me know.

Thanks,
Sharif

**Comment by codebude** [comment]
Hi @SheriffKhan , sorry that I was to slow to respond, before you closed the issue. Can you tell me how you fixed your problem? (It may be helpful for other users, which may get into the same situation.)
