### ISSUE TITLE
QRCoderImageToByteArraySln Missing

### ISSUE THREAD

**Issue by morgan-schwertfeger** [codebude/QRCoder#177]
## Type of issue
[ ] Bug  
[ x ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
I was looking at how to enable this in SSRS which the blog at https://www.sqlservercentral.com/articles/generate-qr-code-barcodes-in-an-ssrs-report-with-the-qrcoder-library suggested adding two outputted dlls (QRCoder.dll and QRCoderImageToByteArray.dll to my GAC)

## Current Behavior
the suggested solution of QRCoderImageToByteArraySln which is referenced and supposedly builds out the QRCoderImageToByteArray.dll is not in the project.   I wanted to know if its now all inclusive in the QRCoder.dll perhaps ??

## Your Environment
VS2017

**Comment by codebude** [comment]
Hi @morgan-schwertfeger ,

I got this question in the past a couple of time. The QRCoderImageToByteArray.dll was not part of QrCoder - even in the past. I think it's a wrapper dll/class written by the article's author. Nevertheless, since more people had the same problem, there's a solution. Check this comment on Stackoverflow, which describes how to use QRCoder with SSRS: https://stackoverflow.com/questions/36811438/how-do-i-show-a-qr-code-in-ssrs/36834961#comment95331061_53835340

**Comment by morgan-schwertfeger** [comment]
Thanks for getting back to me Raffael.  Will check it out, much appreciated.
M.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by alexanderalaamaru** [comment]
@codebude Good afternoon friend, could you help me? I'm running into the same problem and even though I tried to do what you said it doesn't work for me.
