### ISSUE TITLE
How do I create a bar code and not a QR code?

### ISSUE THREAD

**Issue by Sambender9** [codebude/QRCoder#178]
I have created a QR code but I want to create a standard bar code too. I can't seem to find any documentation on that.

**Comment by codebude** [comment]
Since you closed the issue, I assume you found the answer. For all other people, which may step over this question - here is the answer: QRCoder was build to genrate exclusively QR codes. thus other bar codes formats can't be created. For things like classic 2D bar codes you could use libraries like ZXing, etc.
