### ISSUE TITLE
Black border around quiet zone / half modules for triangle shapes like MS HCCB

### ISSUE THREAD

**Issue by SynsoftSolutions** [codebude/QRCoder#183]
## Type of issue
[ ] Bug  
[X ] Question (e.g. about handling/usage)  
[X] Request for new feature/improvement 

Hello,

i am trying to create some sort of custom QR-Code.
Purpose of this code is uniqueness. The decoding app should only recognize this QR Code and not any other QR-Codes that someone could try to decode. It will be used for calling links to a database.

What would be needed is a QR-Code that has a 1 module wide black boarder around its quiet zone and a 4x4 module wide black triangle in the bottom right corner of the QR-Code. Its literaly a 4x4 module square cut in half.

Here is a link to an image illustrating what the qr-code would need to look like. 
https://imgur.com/5tWIINZ

I don't know if the QRCoder library is already capable of doing this, so this is a question if it is possible and how. If it is not possible it would be a request for implementation.

Best Regards

Manuel

**Comment by codebude** [comment]
This is possible by writing your own rendering class. (See this wiki entry as starting point: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers) 
Nevertheless I won't add this as feature to QRCoder because it's too specific. The "official" rendering classes of QRCoder are (in first place) meant to be options for different output formats and not for custom/non-standard QR code adaptions.
