### ISSUE TITLE
Missing trailing CR + LF if field "bill information" is empty

### ISSUE THREAD

**Issue by sensorflo** [codebude/QRCoder#216]
## Type of issue
[X] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
The following is with respect to the standard "Schweizer Implementation Guidelines QR-Rechnung" version 2.0. The chapter 4.2.3 mandates that CR + LF separates fields, as opposed to delimit them. The table in chapter 4.3.3 mandates that the field QRCH/RmtInf/AddInf/AstrdBgkInf "Bill information" is an optional field. That is it must be delivered but can be empty. Thus if the field "Bill information" is empty, and the Alternative scheme parameters are not delivered, then the last 5 characters of the payload must be "EPD\r\n": the "\r\n" separates the field "Trailer" from the necessarily delivered field "Bill information", however "Bill information" is empty.

## Current Behavior
In the above-described scenario, the payload ends with "EPD", i.e. the trailing "\r\n" is missing.

**Comment by codebude** [comment]
Hi @sensorflo ,

At first I thought the library would behave correct, because the standard says that it is ok to remove the trailing "\r\n". But you are right - it should remove only the very last and trailing "\r\n" and not all trailing "\r\n"s... I corrected the behaviour in this commit: https://github.com/codebude/QRCoder/commit/6d657525dc0e6480f760131763e897e9bfa51c2b
