### ISSUE TITLE
Custom quiet zone size

### ISSUE THREAD

**Issue by jasonycw** [codebude/QRCoder#218]
## Type of issue
- [ ] Bug  
- [ ] Question (e.g. about handling/usage)  
- [x] Request for new feature/improvement  

## Expected Behavior
Currently there is only a bool `drawQuietZones` to indicate the margin. However the size of the margin is calculated with `pixelsPerModule`
``` C#
var offset = drawQuietZones ? 0 : 4 * pixelsPerModule;
```
It would be great if there is a exact offset can be input and no need to dynamically generate the margin.

e.g.
``` C#
qrCode.GetGraphic(pixelsPerModule: 5, offset: 3);
```

## Your Environment
* Version used:  1.3.6
* Compiled from source or NuGet package?:  NuGet
* Used ECC-level:  L
* Used renderer class:  Base64QRCode
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  .NET Core 3.1

**Comment by codebude** [comment]
Thanks for your request. However, I have no intention of implementing it. Let me explain why. The quietzone is not set arbitrarily in its width but a "border" prescribed in the official QR code standard. A QR code with a variable quietzone would be by definition no longer a standard QR code. The parameter `drawQuietZones` for suppressing the squeak zone was only introduced to save bytes in case the displaying application itself represents the quietzone or if qr codes are printed on a white background or on paper, for example. (And to be honest even this is not compliant to the standard and something I wouldn't implement again. But for compatibility reasons I will not remove the parameter now, because I fear to break a lot of applications which use it.)

IF you want to have a variable quietzone, you could simply set the `drawQuietZones` parameter to `false` and then take the image object and use the `Graphics`-class to draw a custom quietzone around it. 

I hope you can understand my motivation for not implementing such parameter. Nevertheless - thanks for your time and input. :-)
