### ISSUE TITLE
Is it possible to not render the module, if a part is hidden by the icon

### ISSUE THREAD

**Issue by fluflo** [codebude/QRCoder#231]
## Type of issue
[ ] Bug  
[ x] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
When having an icon in the middle of the QR-Code, the modules of the Code are only rendered, when they are fully visible. 

## Current Behavior
When having an icon in the middle of the QR-Code, it is possible, that only a small part of the module is visible. That way it looks like the Image is just in front of the Code and not a part of it.

## Your Environment

* Version used:  1.3.5
* NuGet package
* Used payload generator:  url
* Used ECC-level:  H
* Used renderer class:  Base64QRCode
* Environment: .NET 4.7.2

**Comment by codebude** [comment]
Hi @fluflo ,

can you provide a sample graphic of what you want to achieve. (An image that shows what is wrong + what you expect.)

**Comment by fluflo** [comment]
Hi @codebude 

I uploaded the 2 versions to imgur: [QRCodes](https://imgur.com/a/Mvkfy5o)

**Comment by codebude** [comment]
Hi @fluflo ,

the expected behaviour (render blocks even partly) was already implemented by this commit/PR: https://github.com/codebude/QRCoder/commit/f6701c1e3b3c7c1342eecf7cd7b8d931b679cd3d I hope you're not mad if I do not merge your's then. (The optional parameters from your PR are obsolete, because we totally removed the "Region" part from the rendering.)
