### ISSUE TITLE
QRCodeGenerator CreateQrCode key not found error

### ISSUE THREAD

**Issue by joshuahxh** [codebude/QRCoder#233]
## Type of issue
[ x ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Steps to Reproduce (for bugs)
using (var gen = new QRCoder.QRCodeGenerator())
{
    var data = gen.CreateQrCode("1230TEST", QRCoder.QRCodeGenerator.ECCLevel.Q);
......
}
error in function PlainTextToBinaryAlphanumeric with key not found.

**Comment by csturm83** [comment]
@codebude This is likely due to the [```alphanumEncTable```](https://github.com/codebude/QRCoder/blob/1e7ebb9e29531880e20fb0bae1281c2d634dcf9a/QRCoder/QRCodeGenerator.cs#L11) lookup array, which was shortened in #194 . ```PlainTextToBinaryAlphanumeric``` uses this array indirectly from a ```Dictionary<char,int>``` created in [```CreateAlphanumEncDict```](https://github.com/codebude/QRCoder/blob/1e7ebb9e29531880e20fb0bae1281c2d634dcf9a/QRCoder/QRCodeGenerator.cs#L1230).

The simple fix would be to restore the previous ```alphanumEncTable``` array.
```
private static readonly char[] alphanumEncTable = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', '$', '%', '*', '+', '-', '.', '/', ':' };
```

**Comment by codebude** [comment]
Hi @joshuahxh ,

thanks for your report. I fixed this in https://github.com/codebude/QRCoder/commit/eb014f990fb1b348be62a47636aa6ef53dfa8d52. Since this is a bug which broke essential functionalities of the QRCoder I immediately will push a new version (1.3.9) to NuGet.

**Comment by codebude** [comment]
Note: Added new test cases to prevent such bugs in the future: https://github.com/codebude/QRCoder/commit/60217f84f298e8b95e60a1122b9b202a152a12aa.
