### ISSUE TITLE
drawQuietZones Question  - is there a way to change the border width?

### ISSUE THREAD

**Issue by EinatGit** [codebude/QRCoder#234]
Hello,

I know that changing drawQuietZones to false removes the white border.
Is there a way to change the border width?
I need the border but I need it to be narrower.
Thank You

**Comment by codebude** [comment]
The border's width is specified/defined in the QR standard. Thus changing the width isn't something which was foreseen/implemented in the library. If you want a non-standard quietzone, just set drawQuietZones to false and add some lines of custom coding to render the custom quietzone onto the resulting QR code graphic.

**Comment by EinatGit** [comment]
I understand.
I will check the add graphic option.
I understand you won't add it as a feature?
Anyway, thank you for the answer :)

**Comment by codebude** [comment]
Yes, I don't plan to add it as feature because it's against the QR code standard. If I would setup QR coder today I maybe even would have added the remove quiet zone feature. The thing is, if I would add this feature, I could add another 100 non standard feature, everytime somebody requests it. All of them may have their purpose, but at the end we had an overly complex library. Thus I like to stay near standard, keep the library simple and ask the requesters to implement their own custom solutions.
