### ISSUE TITLE
Help for 'POM' code

### ISSUE THREAD

**Issue by Illeris** [codebude/QRCoder#239]
Any input/help/docs on how to integrate POM code (https://www.pom.be/en/about) ?

**Comment by codebude** [comment]
Hi @Illeris ,

haven't heard about POM until now. I checked their website but couldn't find a developer documentation. But it looks like, that payments are initiated via http links (they call it POM payment links). From what I've seen the QR codes only contain the http links to the POM payment. So I guess you could just generate a regular QR code and place the POM link inside. But as long as I haven't seen any official documentation this is only a guessing...

Can you provide a developer documentation or at least some samples of POM qr codes?

**Comment by Illeris** [comment]
I’ll ask them. Have no idea it is propriatary or not, but it starts to be hot over here due to the “payconiq” support. It is the most used mobile payments app in our country (acquired by ATOS Worldline a few years ago)

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Raffael Herrmann<mailto:notifications@github.com>
Verzonden: vrijdag 5 juni 2020 7:04
Aan: codebude/QRCoder<mailto:QRCoder@noreply.github.com>
CC: Illeris<mailto:tim.musschoot@outlook.com>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [codebude/QRCoder] Help for 'POM' code (#239)


Hi @Illeris<https://github.com/Illeris> ,

haven't heard about POM until now. I checked their website but couldn't find a developer documentation. But it looks like, that payments are initiated via http links (they call it POM payment links). From what I've seen the QR codes only contain the http links to the POM payment. So I guess you could just generate a regular QR code and place the POM link inside. But as long as I haven't seen any official documentation this is only a guessing...

Can you provide a developer documentation or at least some samples of POM qr codes?

**Comment by codebude** [comment]
After some research I close the ticket now, because POM QR Codes do not contain a special data structure, but only an url ([example code here](https://community.pom.be/hc/article_attachments/360005392939/mceclip0.png)). Payloads with urls can already be generated with QRCoder without any problems.

The "secret" behind POM is, that the url in the POM code redirects to a record at POM.be, which then contains the actual payload data. Without a merchant account at POM it is therefore not possible to create valid POM codes. ([More about this here.](https://www.pom.be/en/receive-payments#Lower))
