### ISSUE TITLE
 [New Feature] Can there be a title in the generated image

### ISSUE THREAD

**Issue by sanshiliuxiao** [codebude/QRCoder#247]
Thank you, this is a good project !

## Type of issue
* Request for new feature/improvement  

## Expected Behavior

I found that there is an icon parameter in this project, so the generated image has an icon.
 Why not add a title parameter, with title when generating the picture.

like this

![](https://i.loli.net/2020/07/26/XUAwq2ircDaSu5h.jpg)

**Comment by paulpeeters** [comment]
Would be especially helpful for Girocode QR to allow the user to check the iban and the name up front. Something like this :

![image](https://user-images.githubusercontent.com/3470523/92099349-aed3f000-edda-11ea-850b-89452f0e49c1.png)

**Comment by codebude** [comment]
Hi @sanshiliuxiao , hi @paulpeeters ,

the whitespace around the QR code is named "quiet zone" in the QR code specification (**ISO/IEC
18004** - google for it like "iso 18004 pdf" - you'll find it. I can't share it here, because it is a licensed document...). 

Furthermore the specification defines that the squeak zone must be exactly 4 modules in size and it must have the same color like the light/bright modules:

> "This is a region 4X wide which shall be free of all other markings, surrounding the symbol on all four sides. Its
> nominal reflectance value shall be equal to that of the light modules."

This quiet zone was defined in the QR standard to make it easier for QR code readers to find and scan the codes. Adding a method to draw content/information into the quietzone would be a violation of the standard, which I want to avoid. Thus I don't plan to add such method to the QRCoder. (I hope you can understand my motivaiton.)

If you want to draw on/into the quiet zone, simply implement your own renderer (by inheriting from the AbstractQRCode class) or alternatively draw your text onto the QR code graphics with help of an graphics library.
