### ISSUE TITLE
Dotnet 5

### ISSUE THREAD

**Issue by PedrooNL** [codebude/QRCoder#258]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ x] Request for new feature/improvement  

## Your Environment

Hi, will qrcoder be dotnet 5 compattible?

**Comment by codebude** [comment]
Hi @PedrooNL ,

QRCoder is already .NET 5 compatible. As stated [over here](However, if you plan to share code between .NET Framework, .NET Core, and .NET 5 workloads, you can do so by specifying netstandard2.0 as your TFM.):

> "[...] However, if you plan to share code between .NET Framework, .NET Core, and .NET 5 workloads, you can do so by specifying netstandard2.0 as your TFM. [...]"

...libraries compiled against .NET Standard 2.0 target can be used in .NET 5 apps. Since QRCoder can be compiled against this target (and QRCoders Nuget package is compiled against this target) this should be no problem.
