### ISSUE TITLE
How to generate customized/stylized QR Code

### ISSUE THREAD

**Issue by Ibrahim-Islam** [codebude/QRCoder#259]
## Type of issue
[x] Question (e.g. about handling/usage)  

Suggestion on how to use this library to generate QR code as shown below with rounded corners and lines?
![qr-code](https://user-images.githubusercontent.com/6401874/96151960-32364480-0f36-11eb-908e-0e59c9bc9af9.png)

**Comment by codebude** [comment]
Hi @Ibrahim-Islam ,

QRCoder can't create such QR codes out of the box, but feel free to implement this feature yourself. Due to QRCoder's [modular concept](https://github.com/codebude/QRCoder/wiki#4-how-does-qrcoders-architecture-look-like), you just have to implement your own rendering class. Have a look at the [QRCode.cs file](https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCode.cs) to check how the general rendering works. Then just copy the QRCode file, rename the class and change the rendering code to your favor/until the results look like your expected output.

**Comment by ovendovitsky** [comment]
@mii9000 Have you solved this issue with rounded corners? If so can you give a solution for this?
