### ISSUE TITLE
Setup the "safety margin" around the QRCode

### ISSUE THREAD

**Issue by MLopes970** [codebude/QRCoder#260]
## Type of issue
[ ] Bug  
[ X ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Your Environment

First of all, thanks for your great job on this project !

In second place, I'm using 2 pixels per module and I would like to keep 0.25cm of safety margin around the code itself. At this moment I have 0.23cm. Is it possible to have the exact value of 0.25cm?

**Comment by pacojones** [comment]
Plus one with the same question 👍

**Comment by codebude** [comment]
Hello @MLopes970 , hi @pacojones ,

the "safety margin" around the QR code is named "quiet zone" in the QR code specification (**ISO/IEC
18004** - google for it like "iso 18004 pdf" - you'll find it. I can't share it here, because it is a licensed document...). 

Furthermore the specification defines that the squeak zone must be exactly 4 modules in size:

> "This is a region 4X wide which shall be free of all other markings, surrounding the symbol on all four sides. Its
> nominal reflectance value shall be equal to that of the light modules."

Since I want to be near standard/compliant to the iso norm, I fixed the size of the quiet zone to the size of 4 modules (=4*pixelsPerModule). If you need a specific size I suggest to load the rendered QR code image/graphic an redraw/enhance the boarder to your needs. (e.g. https://stackoverflow.com/a/14593261)

One thing you should keep in mind: You say you target 0,25cm. Centimeters and pixels don't work well together. You say currently the border is sized 0,23cm. But keep in mind on a screen with another DPI (pixel density) or on another printer with a different PPI setting, you will end up with totally different results. So you application logic should check DPI (for screens) or PPI (if you wanne print) and take this values into consideration when repainting/re-sizing the quiet zones...
