### ISSUE TITLE
Non recognizable QRCode when data to encode exceeds requestedVersion and eccLevel capacity

### ISSUE THREAD

**Issue by dteijo** [codebude/QRCoder#263]
## Type of issue
[X] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
DataTooLongException if data to encode exceeds requestedVersion and eccLevel capacity

## Current Behavior
Generates non recognizable QRCode

## Possible Solution
Check data length with capacity table used to select version when requestedVersion is -1

## Steps to Reproduce
Encode 8 bytes to version 1 with High ECCLevel (capacity is 7)
```
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode("overflow", QRCodeGenerator.ECCLevel.H, false, false, QRCodeGenerator.EciMode.Default, 1);
QRCode qrCode = new QRCode(qrCodeData);
Bitmap image = qrCode.GetGraphic(10, Color.Black, Color.White, true);
```
Generated QRCode:
![non recognizable QRCode](https://i.postimg.cc/WpfJ4gsH/45cfdf08-7726-4c4c-8465-3c386df4a586.png)

## Your Environment
* Version used:  1.4.1
* Compiled from source or NuGet package?:  NuGet
* Environment: .NETCore 3.1

**Comment by codebude** [comment]
Hi @dteijo ,

thanks for pointing out this issue. By now the "DataTooLong" exceptions were only thrown when the programmer didn't set a fixed version. That's because I assumed that if a developer explicitly sets a fixed version (instead of letting QRCoder calculate the optimum version) he or she knows the maximum payload size for this version. But you're right - it doesn't hurt to add some additional checks, thus I added them to the code base. :-) You can find the changes here: https://github.com/codebude/QRCoder/commit/49d5b35e186437c086de152f50a0c7348f7c84cc

Please let me know, if this solves your problem, so that we can close this issue.
If you want to test the changes without compiling QRCoder yourself, you can get the latest build via the MyGet-Nuget-Feed:
https://www.myget.org/F/qrcoder/api/v3/index.json

**Comment by dteijo** [comment]
Hi @codebude ,
problem solved, thanks for your prompt response!
Closed,
