### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by eduardomrp** [codebude/QRCoder#264]
## Type of issue
[ ] Bug  
[x ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior

Hello @codebude ,
Your project is awesome!

I'm using it for the first time and i'm struggling with some parameters.
I need to create a QRCode with the following specifications:

1 - Ecc = M
2 - Type = BYte
3 - Points per Module = 2
4 - Version = 9 (minimal value)
5 - Image dimension = 30mm x 30mm
6 - Security margin = 0,25

Can't you help me?

Thanks
Eduardo

**Comment by codebude** [comment]
Hi @eduardomrp ,

1 => Can be set via function parameter.
2 => Will be handled automatically.
3 => Can be set via function parameter.
4 => Not possible. If you don't provide a version, QRCoder will estimate the smallest version possible. Otherwise you can set a fixed version (e.g. 9) via parameter, but in this case, you have to ensure that not more data is provided than QR code version 9 can take. Setting a minimal version and at the same time let QRCoder scale for higher versions is currently not possible.
5 => Cannot be set directly. The physical output size depends on "pixels per module", the choosen version the the DPI/PPI settings of the target screen/printer.
6 => Security margin is defined by QR code standard to 4 blocks (which means security border will be 4*pixelsPerModule)

The settings which come nearest to your request would look like:
'''csharp
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode("The text which should be encoded.", QRCodeGenerator.ECCLevel.M);
QRCode qrCode = new QRCode(qrCodeData);
Bitmap qrCodeImage = qrCode.GetGraphic(2);
'''

**Comment by dteijo** [comment]
Hi, @eduardomrp,
for specification number 4, you can create QRCodeData with _automatic version_, and then recreate it if obtained version is less than 9:

```csharp
string textToEncode = "The text which should be encoded.";
int minVersion = 9;

QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode(textToEncode, QRCodeGenerator.ECCLevel.M);
if (qrCodeData.Version < minVersion) {
    qrCodeData = qrGenerator.CreateQrCode(textToEncode, QRCodeGenerator.ECCLevel.M, requestedVersion: minVersion);
}
QRCode qrCode = new QRCode(qrCodeData);
Bitmap qrCodeImage = qrCode.GetGraphic(2);
```

**Comment by eduardomrp** [comment]
@dteijo 
Many thanks to both!

**Comment by eduardomrp** [comment]
@codebude and @dteijo

**Comment by eduardomrp** [comment]
@dteijo and @codebude Many thanks to both
