### ISSUE TITLE
Image inside QR code - Specify size of image

### ISSUE THREAD

**Issue by amittleider** [codebude/QRCoder#266]
## Type of issue
[ ] Bug  
[x] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  

## Expected Behavior
I'm wondering if there is (or could be) and API on this library so that I can specify the size of the image to go in the middle of the QR code. Similar to this API: 

```
            var s = System.IO.File.ReadAllBytes(filename);
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(@"https://google.com", QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);

            var bitmap = qrCode.GetGraphic(10, Color.Black, Color.White, (Bitmap)Bitmap.FromStream(new MemoryStream(s)), 30);
```

However, in this API, we specify "30", which means "cover 30% of the qr code with this bitmap image". I'd rather specify something like:

```
            var s = System.IO.File.ReadAllBytes(filename);
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(@"https://google.com", QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);

            var bitmap = qrCode.GetGraphic(10, Color.Black, Color.White, (Bitmap)Bitmap.FromStream(new MemoryStream(s)), 48, 48);
```

Which would mean "Make the image in the middle of the QR code 48 pixels by 48 pixels".

## Possible Solution (optional)
Is there already a way to do this (through either an API or a mathematical equivalent)?

The image below demonstrates it --
There are 3 blue logos, the first is 100x100, the second is 48x48, and the third is 20x20. However, when they are injected into the QR code, the size of the image is ignored and only the default parameter (15%) is accepted.

![image (2)](https://user-images.githubusercontent.com/1625951/101810862-2302eb80-3ace-11eb-8a9a-0c50b32fdb51.png)

**Comment by codebude** [comment]
Hi @amittleider ,
the fact that the parameter refers to the percentage size instead of an absolute pixel size is a deliberate design decision.

**Background:** Depending on the selected error correction level (ECC level), x % of a QRCode may become "corrupted" (or be covered by a logo) before it is no longer readable.

| ECC Level | Recoverable data in % |
|-|-|
| L | 7 |
| M | 15 |
| Q | 25 |
| H | 30 |
(Source: https://en.wikipedia.org/wiki/QR_code#Error_correction)

The fact that the parameter now also works with percentages makes it easy to ensure that the QR code always remains readable. If, for example, you choose ECCLevel "H" for QRCode generation, you should simply make sure that the parameter iconSizePercent is < 30.

> Is there already a way to do this (through either an API or a mathematical equivalent)?

Since you can calculate the size of the resulting QRCode in pixels, you can also derive the value for xxx to render a logo in a certain absolute size.

``` csharp
var filename = @"C:\Users\codebude\Desktop\avatar.png";
var pixelsPerModule = 10;
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode(@"https://google.com", QRCodeGenerator.ECCLevel.Q);
QRCode qrCode = new QRCode(qrCodeData);

//Logo - absolute size calculation
var qrCodeSizeInPixel = qrCodeData.ModuleMatrix.Count() * pixelsPerModule;
var onePercent = qrCodeSizeInPixel / 100d;
var targetFixedSizeOfLogoInPx = 150;
var logoPercentage = (int)Math.Min(100, Math.Round(targetFixedSizeOfLogoInPx / onePercent, 0));

var bitmap = qrCode.GetGraphic(pixelsPerModule, Color.Black, Color.White, (Bitmap)Bitmap.FromFile(filename), logoPercentage);
```
