### ISSUE TITLE
After downloading and compiling and then replaced the older DLL, I am running in to erros

### ISSUE THREAD

**Issue by netrunner1987** [codebude/QRCoder#28]
I want to use the latest, since it has the overload to remove margin on the barcode.  I am getting errors now and need to roll back on to the order dll.  GetGraphics errors on me.  Any one else having issues?

**Comment by codebude** [comment]
Hi @netrunner1987 ,
There are at least two ways to solve this.

1. Add the "raw source" QRCoder project to your main project. (Instead of the DLL.) So you can debug and see what's going wrong.
2. Post you code, where you initialize the QRCode and call the GetGraphics-method. Then I can re-check whats going wrong.

Greetings,
Raffael

**Comment by codebude** [comment]
I removed string interpolation from the SVG in (https://github.com/codebude/QRCoder/commit/646b9fa8cb950118b8dc5598231aa498beed8fe8) because it's an C# 6.0 feature, which only can be compiled with VS2015. For reasons of backward compatibility I removed it. Maybe this solves your error.
