### ISSUE TITLE
special characters encoding

### ISSUE THREAD

**Issue by a4da** [codebude/QRCoder#3]
I've got a problem while trying to encode special characters. 
When using characters like č, š, etc, qr code is generated but can not be decoded. Otherwise it works great.
Is there any way to set encoding to UTF-8?

**Comment by codebude** [comment]
You don't have to set encoding to UTF-8. There was a bug which is fixed by my last Commit https://github.com/codebude/QRCoder/commit/a06d43c0fb1a08524441228f6dc01bc85f766ff9
So it should work now.

Nevertheless some words concerning UTF-8 and QR codes:
In the ISO which describes QR codes there's no UTF-8 in "Byte Mode". For UTF-8 the standard offers the ECI Mode. Unfortunately most QR code readers have not implemented ECI-Mode, but can detect UTF-8 in Byte-Mode. So that's the way I go. UTF-8 is automatically detected and used in Byte Mode.
