### ISSUE TITLE
I am unable to find class SvgLogo in the latest Nuget Package version 1.4.1

### ISSUE THREAD

**Issue by raoufr** [codebude/QRCoder#307]
I am unable to find class SvgLogo in the latest Nuget Package version 1.4.1. Not sure why that is, and whether this will be included in a future release. 

Need to leverage it to embed a logo in the center of a QR code svg string. 

Thanks in advance.

**Comment by codebude** [comment]
Hi @raoufr ,

SvgQRCode is definitely part of QRCoder 1.4.1, but(!) it isn't supported for all target frameworks. Due to a dependency to `System.Drawing` the SvgQRCode is only availble if your application targets (full) .NETFramework (3.5+, 4+ or 5.0+) or .NETStandard2.0. On all other target platforms (e.g. netcoreapp1.x, netstandard1.x, ...) SvgQRCode isn't available.

If you are interested in the technical implementation -> the restriction can be seen here: https://github.com/codebude/QRCoder/blob/master/QRCoder/SvgQRCode.cs#L1
