### ISSUE TITLE
Whitespace is added to generated QR code image (PngByteQRCode)

### ISSUE THREAD

**Issue by ctorx** [codebude/QRCoder#312]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[X ] Request for new feature/improvement  

## Expected Behavior
When using the PngByteQRCode.GetGraphic() the resulting image should have no whitespace around the QR code.

## Current Behavior
Whitespace is added around the qrcode in the resulting image.  

## Possible Solution (optional)
There should be either (1) the option to disable whitespace around the QR code or (2) the ability to specify the amount of whitespace that would include the option for 0.

## Your Environment
* Version used:  1.4.1
* Compiled from source or NuGet package?:  Nuget
* Payload/Encoded text:  999020228
* Used payload generator:  QRCodeGenerator
* Used ECC-level:  Q
* Used renderer class:  PngByteQRCode
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  netcore 3.1

**Comment by codebude** [comment]
Hello @ctorx ,
first of all - the "whitespace" around the QR code is not a peculiarity of the QR coder, but a requirement of the official QR code standard. In the standard this whitespace is called "quiet zone". It is intended to ensure that the QR Code can be recognized by reading devices in the best possible way.

Nevertheless, I understand your requirement and this is not the first time I've heard it. (Because the QR Codes can remain readable even without the quiet zones or the developer can also take care of a sufficient quiet zone himself when embedding the QR Code).
For this reason I added a new, additional and optional parameter "drawQuietZone" (type: bool). If you set this parameter to "false", the quiet zone will not be rendered. You can find hints on how to use it [in the wiki](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#25-pngbyteqrcode-renderer-in-detail).

The parameter is available now [in the CI-build](https://github.com/codebude/QRCoder/packages/1072246) or with the release of the official version 1.4.2 on Nuget. (Official release will follow soon...)
