### ISSUE TITLE
QRCode is not read by default IPhone Camera appliction

### ISSUE THREAD

**Issue by sshousha** [codebude/QRCoder#337]
### Discussed in https://github.com/codebude/QRCoder/discussions/336

<div type='discussions-op-text'>

<sup>Originally posted by **sshousha** November  8, 2021</sup>
We print a QRCode in one of our SSRS reports , the barcode is not read by iPhone. it is working fine with Android. Note that the same iPhone can read other QRCodes (not generated from the DLL) by the default camera application. What  could be wrong.  Here is the code we use:

Public Function QRCoderByteArray(ByVal inputString As String) as Byte()
     Return QRCoder.BitmapByteQRCodeHelper.GetQRCode(inputString, QRCoder.QRCodeGenerator.ECCLevel.Q, 20)
End Function</div>

**Comment by codebude** [comment]
Can you post a sample QR graphic that was generated by your application and that isn't readable by iPhone. I would like to have a closer look.

**Comment by sshousha** [comment]
![image](https://user-images.githubusercontent.com/32600393/140895378-60ce8341-3027-4ab7-85f8-afbd4acd1027.png)
Here you are

**Comment by codebude** [comment]
Hi @sshousha ,

I made some test runs. It looks to me, that the QR codes in general aren't errornous. But when using your sample code from above I also tend to get errors in some QR code readers.  To me it looks like the source of those errors is that your code graphic is really blurry. This may come because you generated the graphic with a pretty huge (pixel-wise) resolution and then resized it. This blurs the code and decreases readability.

Have you tried to generate the codes with a smaller size-parameter? This should ensure that when resizing the code graphics it shouldn't get blurred that much.

Example:
```vb
Public Function QRCoderByteArray(ByVal inputString As String) as Byte()
Return QRCoder.BitmapByteQRCodeHelper.GetQRCode(inputString, QRCoder.QRCodeGenerator.ECCLevel.Q, 2)
End Function
```
(By setting size to 2 instead of 20, the QR code graphic becomes smaller, because less pixels are used for printing the white/black blocks of the code.)

The following graphic was generated with size=2:
![sample_2](https://user-images.githubusercontent.com/2236234/140951039-79f48852-ecdf-42d5-9254-0692ed818a37.png)

If you compare it optically you should see, that the blocks are placed identical to your example. The only difference is the "clear-ness" of the graphic. If you try to scan my sample, it should work - even for iPhones.

Please give a quick feedback, if this solved your problems.

**Comment by sshousha** [comment]
Hello,
 I am afraid the bitmap you sent is not working as well. Can the size of the code be an issue? 

![image](https://user-images.githubusercontent.com/32600393/141135464-c0c6807f-09d0-46f0-98d8-be1e1b07ffef.png)

**Comment by codebude** [comment]
Ok, I just borrowed an iPad and an iPhone from a friend and got the same result. They say "QR code detected" but also "No usbale data" found. If I researched correctly, this is how the QR scanner of Apple's camera app works. I just can't scan any QR code, but tries to parse the content of the QR code and usually expects it to be an URL, a WifiLogon, vCard etc. Seem like it just can't parse you plaintext payload.

Since the QR codes generated with QRCoder are technically fine and 100% standard compliant, I would say this is a software "issue" at Apple's camera app (=nothing I can fix). Thus I will close this issue.

Possible solution: I guess your best bet is to install a dedicated QR code scanner app on your iPhone like https://apps.apple.com/de/app/qr-code-scanner/id1200318119 or alternatively generate QR codes in formats that are accepted by/can be parse by Apple's camera app.
