### ISSUE TITLE
System.Text.CodePagesEncodingProvider.Instance not found error

### ISSUE THREAD

**Issue by naushadck** [codebude/QRCoder#352]
I am getting the following error in the project build.

"CodePagesEncodingProvider.Instance doesn't exists ."

Following code affected.
#if !NET35 && !NET40 && !NETSTANDARD1_3_OR_GREATER
                System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
#endif

#if !NET35_OR_GREATER
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
#endif

I m using .NET 4.7  VISUAL STUDIO 2015.

How can i resolve the above CodePagesEncodingProvider.Instance error ?.

## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment]
Hello @naushadck ,

so you are building QRCoder from code, instead of using the Nuget package, correct?

Usually you shouldn't see this error, because QRCoder defined .NET4.0 as target framework and then this line of code shouldn't be executed. (See here: https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCoder.csproj#L4)
So I guess you changed the target framework for you local QRCoder project to something else/above?

Nevertheless I slightly changed the compilation constants (in this commit https://github.com/codebude/QRCoder/commit/75e0db11e79cbc31c232ce24929ef095b45994d8). Please do a pull (if you don't use Git - download the sourcecode again) and re-try. Let me know if it works.

**Comment by naushadck** [comment]
Thank you for your quick action and reply. I will do so....   Thank you very much........................

**Comment by codebude** [comment]
Please leave a quick feedback (if it worked), when you had time to test it, so that I can close the issue or do further investigation.

**Comment by naushadck** [comment]
I am not sure about steps like pull etc..... I tried to do so. But no success.
So what i did is --- commented those lines in the source downloaded. Now it works. I am using .NET 4.7 with VS 2015.

Please close it....
