### ISSUE TITLE
Generate Base64 encoded QRCode image string

### ISSUE THREAD

**Issue by Z-Clive** [codebude/QRCoder#42]
Hey, codebude,

Thanks for this amazing library.

I'm building a website and needed to generate QRCode for Urls dynamically, and then show them in the webpage. Since there is a way to render Base64 encoded image string in the browser like this:

```
<img src="data:image/jpg;base64,......" />
```

it'll be much better that QRCoder could directly output the encoded string rather than having users transforming its output Bitmap image to the Base64 string.

**Comment by codebude** [comment]
Done with this commit: https://github.com/codebude/QRCoder/commit/28325f91be17790ba09a801def254fa31a542427

Just use "Base64QRCode" instead of "QRCode" class. The GetGraphic-method of Base64QRCode returns a string, which contains the qr code in base64 format. Although there is a new optional parameter "ImageType" in all GetGraphic-methods, which enables you to choose in which file format the image should be converted before saving it as bade64 string.

**Comment by Z-Clive** [comment]
Thank you for your effort! It'll be much friendly to web developer now.
