### ISSUE TITLE
Problem German Umlaute

### ISSUE THREAD

**Issue by jhillmannco** [codebude/QRCoder#43]
Problem with
123456789äüß will return
123456789???
But
Ä123456789äüß returns
Right

Please correct

**Comment by codebude** [comment]
Hello @jhillmannco ,

this isn't really a bug by QRCoder but rather a bug by yours and some other QRCode readers. QRCoder generates valid QR codes. Just try the QR code in the following QR decoder and you'll see that everything is fine:http://qrlogo.kaarposoft.dk/qrdecode.html

## How it has to be done

The problem's source lies in the QR code standard (ISO/IEC 18004). There you can read in chapter 5:

> "[...] byte data (default: ISO/IEC 8859-1; or other sets as otherwise defined (see 6.3.4));"

and in chapter 6.3.4

> "In closed-system national or application-specific implementations of QR Code 2005, an alternative 8-bit character set, for example as defined in an appropriate part of ISO/IEC 8859, may be specified for Byte mode. When an alternative character set is specified, however, the parties intending to read the QR Code 2005 symbols require to be notified of the applicable character set in the application specification or by bilateral agreement."

## What QRCoder does

So this is exactly what QRCoder does. If a payload has to be encoded in Byte-Mode, QRCoder checks if the string can be encoded in ISO-8859-1. If so, it uses ISO-8859-1 encoding, because of the QR code ISO standard. If the payload for example contains asian characters, which can't be encoded in ISO-8859-1, it automatically switches to Utf-8.

## What your QR code app does

Your QRCode app doesn't show the umlauts. In most cases this happens, when QR code readers expect Utf-8 in every case. Hardly spoken, this is the result when somebody implements an app which doesn't observes the standard.

## How I "solved" it

To help you with your trouble, I added an additional parameter on the CreateQrCode-method in QRCodeGenerator-class with this commit: https://github.com/codebude/QRCoder/commit/e47361081f97002a9853dc05d40139d89a775dca .
 So by setting the parameter "forceUtf8" to true, you can tell the QRCoder to encode Byte-mode payloads in Utf8 anytime. Thereby your non-standard QR code reader should be able to read the code. 

But please take note, that you're leaving the standard path, too, by setting this parameter. Also most QRCode readers should be able to handle this mode, because Utf-8 encoded payloads are marked as such, so most readers should be able to detect the forced Utf-8.

**Comment by jhillmannco** [comment]
Perfect Solution !

**Comment by jhillmannco** [comment]
Very Good Library now im gonna replace Fuckuchi LibQrencode with this awesome QRCoder

**Comment by codebude** [comment]
May I ask you, in what project you use the library? If you don't want, no problem, but I'm always interested to see where and how it helps other developers.

**Comment by jhillmannco** [comment]
Hallo
Benutze es es für einen Girocode damit Rechnungen per App damit bezahlt
werden können

Lg
Jürgen
Am 07.07.2016 16:44 schrieb "Raffael Herrmann" <notifications@github.com>:
