### ISSUE TITLE
QR image is printed without the position finder squares 

### ISSUE THREAD

**Issue by Nasser190** [codebude/QRCoder#439]
Dear All
I am using QRCoder C# library with DLL version 1.3.7 NET 4.5, when printing the QR code the QR image is printed without the position finder squares (inner eye) as shown in the below screenshot so the QR will not be readable knowing that if I placed the squares with image editor (i.e. MS Paint) the QR code can be easily recognized 
I am using the following code
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeGenerator.ECCLevel eccLevel = (QRCodeGenerator.ECCLevel)0;
qrCodeData = qrGenerator.CreateQrCode(txt, eccLevel);
QRCode qrCode = new QRCode(qrCodeData);
QRImage = qrCode.GetGraphic(20, Color.Black, Color.White, null, 100);
 
![image](https://user-images.githubusercontent.com/121581819/209906920-cc8dd4b6-85cf-4f0b-b0cc-1362f817757c.png)

Can anyone help me in that issue?

**Comment by Shane32** [comment]
I am unable to reproduce the issue.  Test conditions:
- .NET Framework 4.5 console app (designed in VS 2019)
- QRCoder version 1.3.7

Sample code:
```cs
using QRCoder;
using System.Drawing;

namespace QRCoderTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var txt = "GL_Credit|FJB2236119232453";
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeGenerator.ECCLevel eccLevel = (QRCodeGenerator.ECCLevel)0;
            var qrCodeData = qrGenerator.CreateQrCode(txt, eccLevel);
            QRCode qrCode = new QRCode(qrCodeData);
            var QRImage = qrCode.GetGraphic(20, Color.Black, Color.White, null, 100);
            QRImage.Save("sample.jpg", System.Drawing.Imaging.ImageFormat.Jpeg);
            var p = new System.Diagnostics.Process();
            p.StartInfo.FileName = "sample.jpg";
            p.StartInfo.UseShellExecute = true;
            p.Start();
        }
    }
}
```

Produces this on my computer:
![sample](https://github.com/codebude/QRCoder/assets/6377684/a2a4116f-4591-4722-b33e-5cae2c445940)

With version 1.4.3 and no other changes, this image is produced:
![sample](https://github.com/codebude/QRCoder/assets/6377684/81d12280-778f-4b92-bb5e-1114806dbf98)

**Comment by codebude** [comment]
I even can't reproduce it. Also I'm missing details. What is meant by "when I'm printing"? Seems like here might be the source of the problem. Because the QRCode shown in the issue description seems to be skewed and dizzy - not like an Image saved directly from QRCoder onto disk. In addition I see some kind of watermark on the QRCode, but the code says that no image ist to be set. (GetGraphic call has `null` for the image parameter.) So there seems to be some kind of printing/image manipulation which isn't shown in the code sample above.

@Nasser190  Feel free to re-open the issue in case the problem still persists with the current version of QRCoder. In this case please provide more details on the printing routine you're using.
