### ISSUE TITLE
Is this library still being maintained? Last commit Dec 2021

### ISSUE THREAD

**Issue by ThaDaVos** [codebude/QRCoder#446]
## Type of issue
[ ] Bug  
[X] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Question
As the title depicts, is this library still maintained? Last commit is from December 2021 - we're already in February 2023

**Comment by SupremeManatee** [comment]
Also Im trying to use it in a .NET 7 and it doesn work.... Donno why

**Comment by ThaDaVos** [comment]
> Also Im trying to use it in a .NET 7 and it doesn work.... Donno why

Maybe open a seperate issue @SupremeManatee about your problem, detailing the exact error you're getting, what you've tried already etc

**Comment by codebude** [comment]
@ThaDaVos and now it 2024... And yes, it's maintained. Or let's say: it's again maintained. You're right that I was a long time not actively working on this project, due to private struggle and changes in personal priorities. But as you may have seen in the commit history, it's still alive and a new release will show up soon. :-)
