### ISSUE TITLE
Difficulty finding library dependencies

### ISSUE THREAD

**Issue by stictt** [codebude/QRCoder#450]
Hello, I noticed one problem. The library does not indicate any limitations or requirements. You can understand this only if you open the code like here.
![image](https://user-images.githubusercontent.com/19176407/230822477-19a5b05d-130f-4d34-9b32-0d289b09b233.png)
I suggest that you add platform and limit information to the ReadMe file.

**Comment by pishangujeniya** [comment]
Thanks @lqlam , Even I found little fishy, when I saw the lines https://github.com/codebude/QRCoder/blob/cecf2066d3f3a74b142aaa7c8d9f744c4673118c/QRCoder/QRCode.cs#L9 

It saved me a lot of time. 
I started using the library suggested by you - https://www.nuget.org/packages/QRCoder-ImageSharp

**Comment by codebude** [comment]
Hi @pishangujeniya , hi @lqlam ,

Sorry to hear that you struggled with the library. I tried to document this in the wiki. Check the compatibility matrix over here: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#2-overview-of-the-different-renderers
Seems like this wasn't clear enough. 

I'm also unhappy with the situation and how imports are solved. The thing is: I started QRCoder in 2013 as a fresher. Back then full, classic .NET Framework was state of the art and System.Drawing was available everywhere. So I built QRCoder upon it. Then over the years I tried to add support for more and more .NET variants/versions which lead to the mess (incl. compiler flags) that you pointed out.

Unfortunately I'm constantly in lack of time and in addition are a bit overwhelmed. I would love to give QRCoder the update it deserves, but fear to break it when cutting off loose ends (like older .NET support). 

It's some kind of dilemma. Maybe I can find 1-3 person to build up a team to develop QRCoder 2.0. 
(Yes, I got some cool PRs from single persons, but I haven't merged them, because I feared possible side effects. If we could work/decide as team, I would feel way more confident in updating the sources.)
