### ISSUE TITLE
Resizing Bitmap of the QRCode

### ISSUE THREAD

**Issue by chenchi13** [codebude/QRCoder#51]
I'm trying to resize the QRCode via C# but I lose quality, is there a smart way to do this?

**Comment by codebude** [comment]
How do you try to resize? I reckon you tried to create a normal QR Code via QRCode class and then resize the resulting Bitmap of the GetGraphic method.

In this case it's clear that you get bad quality graphics, because the you are working on a Bitmap which has image information pixel by pixel. When resizing the quality shrinks because you have information loss.

For now I can think of three solutions:

1. When calling the GetGraphic method set the parameter "pixelsPerModule". This parameter tells the QRCoder how much pixels each black (or white) block should have on it's outer sides. So for example: The QR Code exists of 21 blocks. If you set pixelsPerModule to 10 the resulting QR Code will have a width of ~210 pixel.

2. Use the SvgQRCode class instead of QRCode. It returns the QRCode in SVG format which is an vector format. (Vector graphics can be resized without quality loss.)

3. Implement your own renderer. All QRCode types are implemented in the same manner. Just create a new class, ChenchiQRCode.cs for example, which inherits from AbstractQRCode<T>. Then override the GetGraphic method and implement your own renderer. The module information (the white and black blocks) is stored in this.QrCodeData.ModuleMatrix which can be used in the overridden GetGraphics class.


Just let me know if this solved your problem. If you implemented your own QRCode type feel free to push it to this repository.

**Comment by Bhanuprathap** [comment]
Is it possible to set width and height for QR Code in C#?
