### ISSUE TITLE
Strong name neede

### ISSUE THREAD

**Issue by vitlachner** [codebude/QRCoder#54]
Hello, could you sign your library?

**Comment by codebude** [comment]
Hi @vitlachner since the Github repo is meant to be used as "source control" for people who compile the project theirself, It makes no sense to sign it, because I won't upload my own private key for signing. 

So if you want a signed version, just fork the repo or download the source code and sign the assembly yourself. (e.g. with the help of Visual Studio this just takes a couple of seconds.)
