### ISSUE TITLE
[WIP/QRCoder2] Consider Removing Nested Types from Public API Signatures

### ISSUE THREAD

**Issue by csturm83** [codebude/QRCoder#555]
[MS design guidelines on the use of Nested Types](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types) suggests that they should be used sparingly and avoided in public API (amongst other recommendations).

PayloadGenerator comes to mind as well as some public enums in QRCodeGenerator. The nesting of types could be removed where unnecessary.

**Comment by codebude** [comment]
I don't think there's anything to add here. Where it makes sense, we can remove/unnest the nested types.

**Comment by codebude** [comment]
I added this as "decision" to the [descision post](https://github.com/codebude/QRCoder/issues/512#issuecomment-2089212286) of the [meta issue](https://github.com/codebude/QRCoder/issues/512). Thus I'll close this issue here, so that we can mark it as completed/decided in the "things to discuss" list [here](https://github.com/codebude/QRCoder/issues/512#issue-2274270333).
