### ISSUE TITLE
Doesn't work with .Net 3.5 which is the highest version supported by Unity 4.3

### ISSUE THREAD

**Issue by SudhanshuAggarwal** [codebude/QRCoder#6]
Hello!

I am making a project in Unity 4.3 where I need to create a QR code on the screen for the phones to connect to. And I'm having issues including this in Unity as Unity can only support dlls of .Net versions upto 3.5 and this plugin uses .Net 4.0

Is there a possible quick fix for that?
I don't have any experience with .Net and C# outside of Unity so I don't know how this can be done, but this library seems really cool and I will definitely use it if this problem can be solved!

Thanks for your time.

**Comment by codebude** [comment]
Have you tried to set the "Target framework" in MonoDevelop to .NET 4.0?

**Comment by SudhanshuAggarwal** [comment]
Yeah I tried. Then also it gives me the same error.

**Comment by codebude** [comment]
It seems like .NET 4.0 isn't possible when using Unity 4.3. Have you tried the workaround using "services"? (The workaround was described here: http://answers.unity3d.com/questions/691073/unity-43-mono-401-and-the-net-35-to-40-library-iss.html)

Otherwise just clone this Github repo, open it in Visual Studio and compile the library against .NET 3.5. This is definitively possible. If you'll receive still the same error, then there must be something wrong with your Unity setup.

**Comment by SudhanshuAggarwal** [comment]
I didn't try the services method but I did try to build the library against
3.5 using Visual Studio. It recognized the library but wasn't able to find
functions/classes in it. Maybe the services method will work. I'll try
that. I would have taken screenshots for you but I didn't think of
reporting it as an issue at that time.
