### ISSUE TITLE
Errornous QR-Codes when using special amount of chars in input

### ISSUE THREAD

**Issue by Bratmaxe1981** [codebude/QRCoder#65]
Hallo,

ich glaube, das ich einen Bug gefunden habe. Ich versuche einen QR-Code für folgenden Text zu generieren:

[#P-BOF#]
XX
XXX
XXXXXXXXX
Test-Text
XXXXXXXXXXXXX
$XX=255.255.0.0
$XX=10.10.0.254
$XX=
$XX1=16
$XX2=16
$XX3=16
$XX4=16
$YY1=ON
$YY2=OFF
$YY3=ON
$YY4=OFF
$ZZ1=16
$ZZ2=16
$ZZ3=16
$ZZ4=16
$AA1=B
$AA2=B
$AA3=B
$AA4=B
$VID1=1
$VID2=1
$VID3=1
$VID4=1
$VID5=1
[#EOF#]

Generiert habe ich den QR-Code mit folgendem Code:
```
Encoding iso = Encoding.GetEncoding("ISO-8859-1");
Encoding utf8 = Encoding.UTF8;

QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode(iso.GetString(utf8.GetBytes(Text)), QRCodeGenerator.ECCLevel.L);
QRCode qrCode = new QRCode(qrCodeData);
Bitmap qrCodeImage = qrCode.GetGraphic(5);
```

Der so erzeugte QR-Code kann nicht gelesen werden (Versuch mit mehreren Apps und Betriebssystemen (IOS, Androdi). Wenn ich nur einen Buchstaben hinzufüge, oder entferne z.B. von meinem Test-Text, funktioniert der Barcode wieder sofort.

Ändere ich im Code den "PixelPerModule"-Wert von 5 auf z.B: 6 , bleibt der Fehler,
Ändere ich das ECCLevel von "L" auf "M" funktioniert der QR-Code auch, nur genau bei meinen Einstellungen tritt der Fehler auf.

Hoffe der Bug kann auch bei dir reproduziert werden.

**Comment by codebude** [comment]
Hi @Bratmaxe1981 , 

if it's ok for you, I'll switch over to english, because other users get the chance to take part on the discussion. If that's not ok for you, let me know, then I'll switch back to german.

At first, what are you trying to do by Encoding your string to Utf-8 and back to ISO-8859-1? Normally you don't have to do that, because the QrCoder has an automatic check for Encoding. If possible it will decode in ISO-8859-1 otherwise in UTF-8...

The "PixelPerModule"-value doesn't really has an impact on the decoding. It only says how big the blocks should be drawn, but it doesn't change how data is encoded. This value could only be to small for your camera, so that it can't recognize the blicks, but 5 px should be big enough for most readers/cameras.

Now let's come to your problem. I tried what you said and can see your problems partly.
When I encode your text with encoding level m everything works fine with every reader I tested.

When I encode it with encoding level L, I get problems, but only with some readers.

- https://www.codetwo.de/freeware/qr-code-desktop-reader/  -->  can#t read the code
- https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=de --> can read the code
- http://qrlogo.kaarposoft.dk/qrdecode.html --> can read the code and in addition, says that there are no errors. (Check the "debug log" checkbox.)

So it's hard to say if the error is in QrCoder library or maybe in the decoder engines of the other QrCode readers...

**Comment by Bratmaxe1981** [comment]
Hi codebude,
ok I'll try it in english.
I think it is a bug in the QrCoder because if I change the Qualitylevel I can read it with every reader.
I have always expected to get the same result with the same text input, even if I change the Quality Level.

Please try this one. I can't read it with the Android App above:
[http://www.bilder-upload.eu/upload/cc4dd8-1491481977.png](url)
Sometimes the App read the QR-Code, but the result is only a number (192586) not the text.

Thanks and greetings from Willich

**Comment by codebude** [comment]
Hi @Bratmaxe1981 ,

ok, the code you linked to in your last post seems to be defective. I can't decode it with any of my decoders. Could you please post:

- the value/text you have encoded
- the ECC Level you have used
- any other parameters you have set

The I'll try to find some time to start a debugging session, because right now I have no idea what's going wrong.

Kind regards and greetings from Meerbusch ;-)

**Comment by Bratmaxe1981** [comment]
Hi, 

this is the Text I tried to encode:
`[#P-BOF#]\nXX\nXXX\nXXXXXXXXX\nTest-Text\nXXXXXXXXXXXXX\n$XX=255.255.0.0\n$XX=10.10.0.254\n$XX=\n$XX1=16\n$XX2=16\n$XX3=16\n$XX4=16\n$YY1=ON\n$YY2=OFF\n$YY3=ON\n$YY4=OFF\n$ZZ1=16\n$ZZ2=16\n$ZZ3=16\n$ZZ4=16\n$AA1=B\n$AA2=B\n$AA3=B\n$AA4=B\n$VID1=1\n$VID2=1\n$VID3=1\n$VID4=1\n$VID5=1\n[#EOF#]`

But I also found a bug in my function, but it shouldn't have to do anything with this bug.
(I have programmed a function that should delete all spaces in the text, but in this function I also delete all "/r" in the text (after each value). Is there a character limit per line witch I exceeded?

**Comment by codebude** [comment]
I tried again. When I run the code you posted above, with your value, I get a QrCode which works without problems. But after having a closer look to the QR code image, it looks in most points similiar, but with slightly differences. So I'm confused. Why do I get another Qr Code image (compared to the one you posted above) than you, while running the same code...

**Comment by Hydroque** [comment]
Could it be when he reads this data in, the /n are omitted?

**Comment by codebude** [comment]
@Hydroque when "who" reads? QrCoder when parsing the payload or the respective QrCode reader apps? For QrCoder I can say that the \n will be read and parsed. I checked that by debugging as also by scanning the generated code in ECC level L. (Like I said, some readers can read the code and the QrCode debugger doesn't give any errors.)

**Comment by Hydroque** [comment]
For example, reading the data separated by \r\n, "read by line" when concatenating that string above, it could omit these.
