### ISSUE TITLE
Foreground / background color support on UWP

### ISSUE THREAD

**Issue by mtinnes** [codebude/QRCoder#73]
Is there planned support for specifying background/foreground colors when generating the graphic on UWP?

**Comment by codebude** [comment]
Hi Mike,

until now this wasn't planned. But it's a good idea. I just had a look at the source and think this shouldn't be a big problem. I'll try to implement it within the next days.

If you need it faster have a look at line 19-20 in the [BitmapByteQRCode.cs](https://github.com/codebude/QRCoder/blob/master/QRCoder/BitmapByteQRCode.cs#L19). I think changing those lines with the RGB values (0-255 byte value per color channel) should be enough. (Please note: This is an assumption. I'm really not an expert in graphic file formats on byte level. So I have to read up on that subject again.)

**Comment by mtinnes** [comment]
Excellent thank you! At first glance it appears to only support RGB and we need transparency. How difficult would it be to add ARGB?

**Comment by codebude** [comment]
Hi Mika, 

RGBA (or ARGB) / transparency isn't possible. Because the ByteArray returned contains a Bitmap an Bitmaps don't have transparency by their specification. 

For transparency the ByteArray had to contain an image in GIF or PNG format for example. 

Since I implemented the Bitmap generation by manually writing every single byte without using a library this wouldn't be that easy, because PNG is a much more complex format and can't be written that easy byte by byte. 

Background: The Bitmap is created manually because of compatibility. The PCL version of QR coder can run in different environments. And not all of them have all features of System.Drawing namespace. So if I would have used System.Drawing for Bitmap/PNG generation, the library would not run on all systems it could run without using System.Drawing. 

But if you know a raw C# implementation for generating PNG images let me know. Then I'll try to adapt it for QRCoder.

**Comment by Hydroque** [comment]
https://github.com/mattdesl/slim/blob/master/slim/src/slim/texture/io/PNGDecoder.java
Although in java, it isn't that hard to figure out.

**Comment by codebude** [comment]
@Hydroque C# does have libs to save "Image"-objects to a lot of formats (like png, bmp, gif, etc.). And I'm using this for QRCode, SvgQrCode, etc. but not for BitmapByteQRCode. I'm doing so, because this libs/classes/methods for image format conversion are relying on classes from System.Drawing-namespace. And since BitmapByteQRCode was written with the aspiration to run on many platforms as possible, I can't use those helpers from System.Drawing because not every platform where BitmapByteQRCode can be used, supports the full set of System.Drawing. That's the reason why I don't use the given helpers.

There are two versions of QRCoder. "Full Stack" and "PCL". FullStack ist compiled against the normal .NET Framework. There I use all the System.Drawing stuff. But for PCL version which runs on lots of platforms, I deliberately dropped the System.Drawing stuff, to keep multiplatform-support. That's why this method returns a Bitmap as byte array. Bitmaps are well known, the format is easy and there is a way to use Bitmaps on on nearly any PCL compatible platform.

Last but not least: You're talking about "raw" formats. Ok let's assume I switch from Bitmap to any "raw" format. Which format should I use? Which has the widest support on all PCL compatible platforms? Do you have a special, standardized raw-format in mind? (And if so, does it support transparency?)

**Comment by Hydroque** [comment]
Allow the first 8 bytes of a file to be unsigned ints of width and height. Follow this by the image data as binary. You might want to include the channels as the 9th byte and perhaps a file header 'RAW'.

As seen in my XMI project (file format for games), 
```
fos.write(new byte[]{(byte)'x', (byte)'m', (byte)'i'});
		fos.write(new byte[]{ // width, height
				width_b[0],
				width_b[1],
				height_b[0],
				height_b[1]
			});
		fos.write(image.getColorModel()); // components
		fos.write(image.getCompression()); // compression type
		fos.write(Bitwork.intToByte(image.getBody().length)); // body length
		fos.write(image.getBody()); // body
```

The downside is they need an additional step for processing to other formats, which IS NOT HARD because there exist libraries that convert raw image data into a specified format.

The format suggests no standard compression. It would look like, (4 is the rgba) (0 is just pixels, colloquially raw) Where each byte is as a number (excluding the 'r'g'b'a')
X,M,I,0,128,0,128,4,0,r,g,b,a,r,g,b,a,r,g,b,a,r,g,b,a...

**Comment by codebude** [comment]
Since the initial request was solved, I'll close this issue. The discussed new type "PngByteQRCode" can be found in this new issue: https://github.com/codebude/QRCoder/issues/79

**Comment by tomekziel** [comment]
Regarding colors - I will leave a link here for future reference: https://github.com/tomekziel/QRCoder/
It does contain coloring system which allows to customize color of each part of QR-code separately
