### ISSUE TITLE
Plans to support QRCode renderer on .NET Standard 2.1?

### ISSUE THREAD

**Issue by leopignataro** [codebude/QRCoder#77]
Dear QRCoder team,

First of all, great work on QRCoder!

I'm choosing a QR Code library for a .NET Core 2.0 project and QRCoder is looking very promising. I'm well aware of the difficulties to work with graphics on .NET Standard 1.x and even 2.0 because of the missing classes on the `System.Drawing` namespace, so I totally get that only the `BitmapByteQRCode` renderer is available for .NET Standard.

Microsoft has promised to fill that gap for .NET Standard 2.1, to be released by the end of this year. I would like to know if you have plans to extend the support for the advanced renderers, more specifically the `QRCode` renderer, once .NET Standard 2.1 is out.

Thanks!

**Comment by codebude** [comment]
Hi @leopignataro ,

thanks for your request. If possible we will add QrCode for .NET Standard 2.1. I think I'll add 2.1 as additional target in the NuGet package so that there will be both, 1.6 (for backwards compatibility) and 2.1 inside the NuGet package.

I'll added a reminder to my calendar to re-check this topic at the end of the year. Otherwise, you can also re-open this ticket, when .NET Standard 2.1 was released.

**Comment by leopignataro** [comment]
OK, thanks!

That's the info we needed (beside our other question #78) to make a decision to go with QRCoder!
