### ISSUE TITLE
Could be a .NET Standard / .NET Core library ?

### ISSUE THREAD

**Issue by ignatandrei** [codebude/QRCoder#85]
Could be a .NET Standard / .NET Core library ?

**Comment by codebude** [comment]
@ignatandrei Can already be used in .NET Standard projects. Just take the package from Nuget. It contains three binaries. (One compiled against .NET 4.0, one compiled against .NET 3.5 and a PCL version, which should work for .NET Standard/.NET Core projects.). Nuget should automatically fetch the right binary version from the package.

If I missunderstood your question, please clarify what you meant.

**Comment by ignatandrei** [comment]
It should be a .NET Standard 1.5  project in VS2017. It is not the same with PCL

**Comment by codebude** [comment]
What would be the benefits of having a .NET Standard version in addition the existing .NET4 and PCL versions?

**Comment by codebude** [comment]
I had a look into it...  
I tried to create a .NET standard library (2.0) project and add the existing code. Since the namespace/lib *System.Drawing* is still missing in ,NET Standard I had to remove the most of the QRCode renderes because they rely on classes out of this namespace. (Yes, I could add an external reference to another graphics library and rewrite the code, but the target of QRCoder was to use as less external references as possible.)

So if I would create a .NET Standard version, it had exact the same functions like the PCL version, which is already available. If I'm not wrong, the PCL version already can be used in .NET Standard projects/apps. So I don't see the benefit to build an additional .NET Standard version of QRCoder.

All in all I have to admit, that I haven't spend that much time on the .NET Standard and .NET Core framework. So if I missed something, which would definitely speak for an .NET Standard version, please let me know. I'm always interested to broaden my horizon.

**Comment by codebude** [comment]
So I steered a middle course. I added .NET Standard 2.0 as additional compilation target: https://github.com/codebude/QRCoder/commit/ce48070b106fb792690895f3d4d2ed2f078cfcdc

From the next release on, the Nuget package will also include a .NET Standard 2.0 binary. Nevertheless I won't drop the PCL version, because for the .NETStandard2.0 version an external dependency is needed (for some System.Drawing tasks). Since this dependency is not available for all platforms, I keep the PCL version as fallback for non-supported platforms.
