### ISSUE TITLE
why not suppert QRCode? .net core 2.0

### ISSUE THREAD

**Issue by 18965824402** [codebude/QRCoder#86]
//using (QRCode qrCode = new QRCode(qrCodeData))
                    //{

                    //    pictureBoxQRCode.BackgroundImage = qrCode.GetGraphic(20, Color.Black, Color.White,
                    //        GetIconBitmap(), (int)iconSize.Value);

**Comment by codebude** [comment]
Because QRCode uses the Bitmap/Image classes from System.Drawing which aren't available in .NET Core 2.0 (as told here: https://github.com/dotnet/corefx/issues/18649#issuecomment-295574882 ) If this info is outdated - please let me know.

You could use BitmapByteQRCode for example - it's .NET Core 2.0 compatible: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#24-bitmapbyteqrcode-renderer-in-detail

**Comment by 18965824402** [comment]
how  add  icon ?   Bitmap Image = qrCode.GetGraphic(10, "#000000", "#FFFFFF", GetIconBitmap(), (int)8);

**Comment by codebude** [comment]
Icons aren't supported in BitmapByteQrCode for now. (Have a look at the documentation: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#24-bitmapbyteqrcode-renderer-in-detail ) They are only available in QrCode-renderer, but this isn't compatible to .NET Core due to the missing System.Drawing namespace. But feel free to implement icons for BitmapByteQrCode and send a pull request.

**Comment by 18965824402** [comment]
https://github.com/zkweb-framework/QRCoder     This is achieved

**Comment by codebude** [comment]
Added .NET Standard 2.0 as additional compilation target. From the next release on, the Nuget package will also include a .NET Standard 2.0 binary: https://github.com/codebude/QRCoder/commit/ce48070b106fb792690895f3d4d2ed2f078cfcdc
