### ISSUE TITLE
Empty rows/columns in QR code generation

### ISSUE THREAD

**Issue by ghidosoft** [codebude/QRCoder#90]
Hello,
I'm generating QR codes and using directly the data matrix to output the black rectangles (I'm not drawing on screen).
The output QR is readable however the `ModuleMatrix` contains padding lines and columns. This is the output I get:
![image](https://user-images.githubusercontent.com/701065/31230418-4095aa1c-a9e4-11e7-98fd-8e524a5c8be5.png)

I expected the QR to fill completely my red bounding box.

This is the code I'm using - `Rectangle` is a custom class that is used in other parts of the project and get rendered correctly.

```c#
public IEnumerable<Rectangle> Generate(string value, double width, double height)
{
    using (var generator = new QRCodeGenerator())
    {
        using (var data = generator.CreateQrCode(value, QRCodeGenerator.ECCLevel.Q))
        {
            var moduleWidth = width / data.ModuleMatrix[0].Count;
            var moduleHeight = height / data.ModuleMatrix.Count;

            var y = 0;
            foreach (var line in data.ModuleMatrix)
            {
                var x = 0;
                foreach (bool value in line)
                {
                    x += moduleWidth;
                    if (value)
                    {
                        yield return new Rectangle(x, y, moduleWidth, moduleHeight);
                    }
                }
                y += moduleHeight;
            }
        }
    }
}
```

Thank you

**Comment by codebude** [comment]
Hi @ghidosoft ,

that's a "feature not a bug". Those whitespace is an official part of the QR as defined in ISO norm. Most people don't know this, because QR codes most times are printed/shown on white surfaces where one might think, that the whitespace is part of the background.

The whitespace, official called "quiet zones" is part of the QR code, for better readability. (So that scanners can see where the QR code begins and ends.)

In my [QRCode-renderer](https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCode.cs) there is a flag called "drawQuietZones". When this is set to false, this quiet zones are ignored. You can orientate on my code. The quietzones are 4 blocks per side. So just skip the 4 first lines/cols and the last 4 lines/cols when iterating through the raw QR code data.

**Comment by ghidosoft** [comment]
Hi @codebude, thank you very much for your answer.

I saw the `drawQuietZones` flag on the renderer and I thought that it was the renderer which added the quiet zone and not the generator.

Maybe it could be nice to add the `drawQuietZones` directly to `QRCodeGenerator`, for now I simply remove the first/last 4 rows/cols from the output matrix. I will then add the quiet zone separately, I need that to be customizable, despite the QR standard.

**Comment by codebude** [comment]
> Maybe it could be nice to add the drawQuietZones directly to QRCodeGenerator, for now I simply remove the first/last 4 rows/cols from the output matrix.

Since the quietZones are part of the QR code, I think the decision (if they should be removed) should be made in the rendering component. So my philosophy is to generate valid (in terms of the ISO norm) qr code data. If then someone want's to render it without the quietZones or in fancy colors, he can change it in the way he renders the data. That's why I added the flag to the render.

Moving the flag to the generator part would, in addition, also lead to breaking changes. Because all rendering components were written under the premise that the data includes the quietZones. 

Kind regards,
Raffael
