### ISSUE TITLE
Bitpacked QR Code Render

### ISSUE THREAD

**Issue by Hydroque** [codebude/QRCoder#92]
For each tile as a square, we could have a bitpacked version (ultimate compression) of the QR code to render procedurally. For example, each square is a 0 or 1 and 1 means colored. I'm sure someone could use this. This can easily be transferred into coordinates for texturing.

**Comment by codebude** [comment]
Hi @Hydroque ,

but this wouldn't be a renderer because it does not output a viewable format, but it would be more like an intermediate format, which could be used for easy implementation of renders.

And I think exactly this exists already. The usage of QRCoder looks as follows:
1) Create instance of *QRCodeGenerator*-class (e.g. 'generatorObj')
2) Call 'CreateQrCode' method of the generatorObj-object. It outputs an object of type *QRCodeData* (let's call it 'dataObj')
3) Put the dataObj into any render-class to get a 'visual representation'

This dataObj from step 2 has a property called 'ModuleMatrix'. This is an list of type *BitArray* and contains a 1/true for a colorful block and a 0/false for a non-colored block. It is used in all renderer-classes.

Is this, what you meant with your issue? Or did I understand you wrong?

**Comment by Hydroque** [comment]
Misunderstanding. A uniform way to return this data matrix as a stream, rather than matrix, and have a renderer output a file with header and size, rowsize stuffed in that header. This is for people who want to load such data and render it themselves later on.

**Comment by codebude** [comment]
Would you prefer an human readble format or the smallest possible format?
a) Human readable: Code saved as text file. 0 for dark box, 1 for light box. (Which would result in 1byte per block.)
b) Smallest possible: Use shift black/white value as bits on to bytes. So that 8 modules could be saved in one byte.

In addition - what do you think about .zipping the outputfile, to save more space?

**Comment by Hydroque** [comment]
Binary file, and you can gzip if you want.

**Comment by codebude** [comment]
Ok, sounds good. But I think I will implement this functionalty as "export"-functions besides the ModuleMatrix in *[QRCodeData](https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCodeData.cs)*-class instead of creating a new rendering class. Because this is more of an "alternative data representation" then a visual representation (what would be the expected output of a "renderer").

**Comment by codebude** [comment]
Hi @Hydroque ,

I added the export feature within this commit: https://github.com/codebude/QRCoder/commit/fe05b041a179c37f8742e8c374b5ec42e21c97ee

The QRCodeData-class now has two more methods. One for generating raw data as byte[] and one which generates raw data and saves it as file. I separated this functions, because the file class isn't available when compiling as PCL. With help of the separation PCL users at least are able to generate the raw data byte[] and can save it then on their own.

I also added a constructor to build an QRCodeData object from a rawData file or a rawData byte array. (It's more for test purposes, because I think in most of the cases the exported raw data won't be imported in QRCoder again, but used in another application.)

No let's come to the format. It's really simple:
1 byte = Length of the QR code side (as int)
2..n byte = Black/white modules. Each byte contains 8 modules. The bits representing the QR code from top to bottom, left to right.

Optional the raw export can be encoded via deflate. A quick test gave the following results:
Payload: 0123456789
ECC-Level: L
Saved as Bitmap (with QRCode) => 1.009.254 Bytes (~985 KB)
Saved as PNG (with PNGByteQRCode) => 429 Bytes
Saved as raw (without compression flag) => 107 Byte
Saved as raw (with compression flag) => 87 Byte

I'll add some more details/documentation to the wiki in the next days.

**Comment by Hydroque** [comment]
Since QR codes are 2 dimensional bar codes, I believe a short would be enough to store 177*177(31,329) as per your *. Is this int signed or unsigned? I recommend it to be unsigned. Also, go ahead and add a 2 or 3 char file signature (in plain text characters) with a trailing \0 or space. GZipped files shouldn't have this file signature.

**Comment by codebude** [comment]
1) "I believe a short would be enough to store 177*177(31,329) as per your *" - In this case I wouldn't store 31329 but 177. And I'm not saving an int but a byte. (Sorry, I was unclear in that point.) So The first byte in the raw file takes the value of the side length. (A short 16-bit/2 byte would eat up more space.)
2) The file signature is a good idea. I think I'll use "qrru" as acronym for "QR raw unzipped".
3) Why not append the file header before the zipped data? (Otherwise the signature is useless, because one cannot now, that the file is zipped and so will not see the header.) When adding the signature in front of the zipped data, e.g. "qrrz" (=QR raw zipped), one could see what type of file it is and remove the signature before unzipping.

**Comment by Hydroque** [comment]
Okay so you store the size for the computer to compute then allocate data. Got it.
qrru is too long. Most, if not all, files are 3 letters then a whitespace or null.
Because a gz file is its own distinct file and when you open it for reading via stream it gets weird having to do some pointer arithmetic to get out the file signature.

**Comment by codebude** [comment]
Hm in C# it isn't hard to skip first bytes (=signature) before decompressing, but maybe in other languages it is hard. So I accept your point.

Regarding the signature. Is there an source with an "official" list of three-letter-acronyms for filetypes? (I don't want to use a filetype-acronym which maybe is used by another popular filetype. Yes I understand that anyone can invent it's own and that it is impossible to avoid all conflicts, but with an list of the most popular ones I could avoid at least conflicts with those.)

**Comment by Hydroque** [comment]
https://en.wikipedia.org/wiki/File_format#Magic_number

**Comment by codebude** [comment]
Hm the wiki article about magic numbers doesn't give a list. More than that it gives "GIF87a" as example, which is 6 chars long (while you said 4 chars is enough). 

But I found this article:
https://en.wikipedia.org/wiki/Magic_number_(programming)#Magic_numbers_in_files

And especially this list...
https://en.wikipedia.org/wiki/List_of_file_signatures
...which shows that most fileformat have 4 or more byte signatures. So I think to keep the "uniqueness" I will use 4 chars (=4byte). I prefer to use "qrra" (for: QR ra(w)).

**Comment by codebude** [comment]
Ok, I checked those three lists, which are really big:
http://www.garykessler.net/library/file_sigs.html
https://www.filesignatures.net/index.php?search=qr&mode=EXT
https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/List_of_file_signatures.html
...and found only one file which starts with QR (qrp=QR report). So maybe it's safe to stay with a three-letter-acronym (qrr). I'll think a night about it...

**Comment by codebude** [comment]
Hi @Hydroque 

added file signature in https://github.com/codebude/QRCoder/commit/b268d2b0721028caef00e3d2afd1f79f27dbf7f2  
See example file: [raw.txt](https://github.com/codebude/QRCoder/files/1392412/raw.txt)  

File format is now:

| Byte index| Description |
| --- | --- |
| 0-2 | Signature (QRR) |
| 3 | Signature terminator (0x00/NUL) |
| 4 | QR code side length |
| 5-n | Payload |


In addition to that, I made some changes to the "compression" flag. I changed the boolean flag (compress/no compression) with an enum (called "Compression"), so that the user can choose between the values "Uncompressed", "Deflate", "GZip" when ex- or importing raw-data. Changes can be seen in: https://github.com/codebude/QRCoder/commit/17a1adeb9fc9f9b1cf89cad72974b94b4ec5af88

If you see something that should be changed, let me know. Otherwise I would write the wiki posts regarding this functions and then close this issue.

**Comment by Hydroque** [comment]
I wonder if it is worth including information about the QR-generated code, like a sub header for optional metadata - to make loading more complete.

**Comment by codebude** [comment]
About what kind of information for the subheader are talking? If we take that raw-export for that what it is, the smallest possible export of all information needed for rendering, than I can't imagine what information may be that useful, that they are worth to bloat the footprint with it. But I like to listen to your reasons. So could you please explain?

**Comment by Hydroque** [comment]
I am asking if the library needs anything beyond what is exported.

**Comment by codebude** [comment]
Hi @Hydroque ,

I don't think that the lib needs anything beyond the exported data. Since you told me, you never actively used the lib, let me roughly outline the process.

**QRCodeGenerator**-class  
+ Takes: payload, qr config parameters, etc.  
+ Generates: Instance of *QRCodeData*  

(QRCodeData contains the modules/black-white-dots as also the QR-Code version number (int). Not more, not less.)  

**"RandomRenderer"**-class  
+ Takes: QRCodeData instance
+ Generates: Random output format (usually a graphical representation of the QR Code)

Now let's look at our raw export. It contains the modules and the QR code's side-length. Since the QR code version (part of QRCodeData-class) can easily be calculated from the side-length, our raw export contains the same information than the QRCodeData instance.

The new constructor of the QRCodeData class, which takes a reference to a raw-data-file or an byte[] of raw data, fills its ModuleMatrix-array from the raw-data's module information and sets the QRCodeVersion property by inverse calculating it from the given side-length.

Since the raw data contains all information of the QRCodeData-instaces, which are the only source of knowledge for all rendering classes, I think its consistent/complete and doesn't need any additional header information.

**Comment by codebude** [comment]
Just added a wiki-page right now: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-raw-data-export

Please let me know, if you miss anything.

**Comment by Hydroque** [comment]
Well I was thinking more along the lines of the square distance of the modules.

**Comment by codebude** [comment]
Why should we save the square distance? This is raw data - like vector formats this hasn't a defined size. It's up to the user/rendering application to choose the module size by their self.

**Comment by Hydroque** [comment]
Hi, I edited the wiki for spelling and meaning and redundancy. I stopped halfway because I got bored, which is at the end of the file format table.

**Comment by Hydroque** [comment]
Hi, I finished editing the wiki page. I hope you love it.

**Comment by codebude** [comment]
Hi @Hydroque , thanks for your support. Looks good. :-)
