### ISSUE TITLE
SwissQRCode - Additional Info

### ISSUE THREAD

**Issue by mHCio** [codebude/QRCoder#93]
Hi,

is it possible to  set the additional Info inside the QRCode ?

Thank you very much

**Comment by codebude** [comment]
Hi @mHCio ,

yes it is. When you use the SwissQRCode payload generator, then you have to pass an object of type "SwissQRCode.Reference" as show here:
https://github.com/codebude/QRCoder/wiki/Advanced-usage---Payload-generators#316-swissqrcode-iso-20022
The reference class has field/property called "unstructuredMessage". This is the additional information field. 

If you want to know why it's named "unstructuredMessage" instead of "additional information" have a look at the SwissQRCode specification: https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-de.pdf

On page 21 (Table 6) the field is labeled "Ustrd" or "Unstrukturierte Mitteilung". (Additional info/Zusätzliche Information is just the "description", but not the technical fieldname.)

I hope this is the information you searched for. If not, let me know.

**Comment by mHCio** [comment]
Hi @codebude,

thank your for this fast answer.
Which ReferenceType i have to use?

Best regards

**Comment by codebude** [comment]
If you want to give a reference you have to choose either "SCOR" or "QRR". Non can only be used when you don't want to send a reference text. If you want to generate a "QR Rechnung" than you should use reference type "QRR". As I understood "SCOR" shall only be used for creditor references.

**Comment by mHCio** [comment]
Yes, it works !

Thank you very much

**Comment by hosseinGanjyar** [comment]
@mHCio please send me a contact mail?
