### ISSUE TITLE
SwissQrCode: Optional Paramter "Zusätzliche Informationen"

### ISSUE THREAD

**Issue by parabolika66** [codebude/QRCoder#94]
Request for improvement:
The SwissQrCode payload generator does not come with optional **parameter "Zusätzliche Informationen"** as specified in ISO-20022. At least the parameter is not mentioned in the wiki. Please add as described on page 21 in the specificaton (https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-de.pdf).
Thank you very much.

**Comment by codebude** [comment]
Hi @parabolika66 ,

the field exists already. I just used the "technical name" as described in the ISO document. Since someone already asked this question, I like to refer to his thread: https://github.com/codebude/QRCoder/issues/93

If something isn't clear or if you have more questions, feel free to re-open the ticket.

**Comment by parabolika66** [comment]
Thanks for your quick answer!
