### ISSUE TITLE
Swiss QR Code: ZipCode is alphanumerical

### ISSUE THREAD

**Issue by parabolika66** [codebude/QRCoder#97]
Hi there
Suggestion for minor improvement:
As per definition the zip code in Swiss QR Code is alphanumerical.
In the current implementation only digits are allowed. Think of zip codes in the UK, e.g. "E2 8JL".
There is an official validation platform to test the QR codes: https://qr-validation.iso-payments.ch. According to the specs there, characters included in the following regex pattern are allowed:
([a-zA-Z0-9\.,;:'\ \-/\(\)?\*\[\]\{\}\\`´~ ]|[!"#%&<>÷=@_$£]|[àáâäçèéêëìíîïñòóôöùúûüýßÀÁÂÄÇÈÉÊËÌÍÎÏÒÓÔÖÙÚÛÜÑ])*
Thank you

**Comment by parabolika66** [comment]
The same goes for "street". Numbers should be allowed there as well (same regex pattern). E.g. a P.O. box, which often contains a number ("Postfach 3000").

**Comment by codebude** [comment]
Hi @parabolika66 ,

thanks for your feedback. I hope I can fix it during the weekend. But if you can and want, feel free to fix it by yourself and sent in a pull request at Github.

**Comment by parabolika66** [comment]
Hi @codebude ,
your welcome and thanks to you. I am evaluating the library on a spec level, so we are not in a hurry yet.

**Comment by codebude** [comment]
Hi @parabolika66 ,

during the development I used the official SwissQRCode spec ( https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-de.pdf ). In this document the zipcode (technical name: PstCd) is described as "a field with a maximum length of 16 chars". No further restrictions. That's why I added some additional regex to get some kind of validity check.

But if you say the official validation tool has some more specific rules, I'll update the library against those rules. So I registered for the validation tool, now. Unfortunately my registration is still pending. So I have to wait before I can fix it.

**Comment by codebude** [comment]
@parabolika66 - now I got access to the validation platform. But I can't see the specifications you named. From where do you got this regex? On the validation platform there's only the official specification document and this says: 

> According to the Swiss standard, in the Swiss QR Code, for reasons of compatibility
with the Swiss Implementation Guidelines for Credit Transfers for the ISO 20022
"Customer Credit Transfer Initiation" message (pain.001), only the Latin character set
is permitted.

**Comment by parabolika66** [comment]
Hi @codebude
I found the information re character set in the written spec very unprecise, that‘s why I made some tests against this validation tool. 
I generated a qr code with invalid characters (https://qrcoderechnung.ch/qr) and tested it on the validation platform. It showed an error with a link to the specs. In this tree view you can check all fields and their patterns. 
I am not at the office today, so can‘t provide any screenshots.

**Comment by Raydir** [comment]
Hi @codebude 
I found your issue here on base of a problem with the street attribute- but i agree with @parabolika66:
based on [six-interbank-clearing.com](https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/archives/implementation-guidelines-ct/implementation-guidelines-ct_v1_6.pdf) and the validation portal the regex pattern would be:

([a-zA-Z0-9\.,;:'\+\-/\(\)?\*\[\]\{\}\\`´~ ]|[!"#%&<>÷=@_$£]|[àáâäçèéêëìíîïñòóôöùúûüýßÀÁÂÄÇÈÉÊËÌÍÎÏÒÓÔÖÙÚÛÜÑ])*

----
As  a sample for the street attribute:
Clinique du luminaire
rue du 31-Décembre 38
1207 Genève
---

As you see there are also street names in switzerland that contain numbers (31-Décembre) in them, which are not the streetnumber (would be 38 in the sample).

Any chance you get that fixed in your library soon?

**Comment by codebude** [comment]
Hi @Raydir , hi @parabolika66 ,

sorry that this took so much time. I did some more tests with the official validation tool and added the Regex pattern you posted to QRCoder. You can find it in this commit: https://github.com/codebude/QRCoder/commit/0a77cd840a9b22a67b4811e68ea7922e5047a14f

l also added this pattern as check for the name and city field (since the validation tool did so, too). Thanks again for your input and your patience.

**Comment by Raydir** [comment]
Hi @Codebude

I'll send this info to our developers so they know that you resolved this issue.

Thanx a lot!

**Comment by codebude** [comment]
Hi @Raydir ,

just keep in mind that this is fixed only in source base by now. It's not in the Nuget package. But I'll release a/the new version on Nuget in the next couple of days.

**Comment by Raydir** [comment]
sure thing thanx.

**Comment by codebude** [comment]
Hi @Raydir , @parabolika66 - it took some time, but this changes are part of the official Nuget package now. Feel free to use [version 1.3.3 from Nuget](https://www.nuget.org/packages/QRCoder/) to keep alway up-to-date.

**Comment by Raydir** [comment]
Hey Codebude
I'll send this info to our developer.
Thanx!
